// Code generated by github.com/orhanbalci/emojic/emojic-gen DO NOT EDIT.

// Source: {{ Link }}
// Created at: {{ Date }}

use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static!{
    pub static ref GEMOJI_MAP: HashMap<&'static str, &'static crate::Emoji> = [
        {{ Data }}
    ].iter().copied().collect();
}

// EOF