// Code generated by github.com/orhanbalci/emojic/emojic-gen DO NOT EDIT.

// Source: {{ Link }}
// Created at: {{ Date }}

use lazy_static::lazy_static;
use std::collections::HashMap;
use regex::Regex;




lazy_static!{
    static ref ALIAS_REGEX: Regex = Regex::new(
        r":(\S*):"
    ).unwrap();

    static ref GEMOJI_MAP: HashMap<&'static str, &'static str> = [
        {{ Data }}
    ].iter().copied().collect();
}

pub fn parse(inp:&str)->Option<super::constants::Emoji>{
    ALIAS_REGEX.captures(inp).and_then(|cap|{
        cap.iter().next()?.and_then(|v|{
            if GEMOJI_MAP.contains_key(v.as_str()){
                Some(super::constants::Emoji(GEMOJI_MAP.get(v.as_str()).unwrap()))
            }else{
                None
            }
        })
    })
}




