// Code generated by github.com/orhanbalci/emojic/emojic-gen DO NOT EDIT.

// Source: {{ Link }}
// Created at: {{ Date }}

    {{ Data }}


pub struct Emoji(&'static str);

use std::fmt;
impl fmt::Display for Emoji {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{})", self.0)
    }
}

pub struct EmojiWithTone<'a> {
    pub one_toned_code: &'a str,
    pub two_toned_code: &'a str,
    pub default_tone: &'a str,
}

impl EmojiWithTone<'_> {
    pub const fn one_toned(code: &'static str) -> Self {
        EmojiWithTone {
            one_toned_code: code,
            two_toned_code: code,
            default_tone: "",
        }
    }

    pub const fn two_toned(mut self, code: &'static str) -> Self {
        self.two_toned_code = code;
        self
    }

    pub const fn default_tone(mut self, tone: &'static str) -> Self {
        self.default_tone = tone;
        self
    }
}