// Code generated by github.com/orhanbalci/emojic/emojic-gen DO NOT EDIT.

// Source: {{ Link }}
// Created at: {{ Date }}

#![allow(unused_imports)]

use crate::Tone;
use crate::Gender;
use crate::Hair;
use crate::Pair;
use crate::emojis::OneOrTwo;
use crate::emojis::TonePair;
use crate::emojis::Family;

/// Matches string (without colons) to emojis
pub(crate) fn matching(s: &str) -> Option<&'static crate::Emoji> {
	let len = s.len();
	let bytes = s.as_bytes();

	if len == 0 {
		None
	} else if len == 1 {
		match bytes[0] {
{{ SingleBytes }}
			_ => None
		}
	} else {
		let first = bytes[0];
		let sec = bytes[1];
		let rest = &s[2..];

		match first {
{{ TwoBytes }}
			_ => None
		}
	}
}

// EOF