// Code generated by github.com/orhanbalci/emojic/emojic-gen DO NOT EDIT.

// Source: {{ Link }}
// Created at: {{ Date }}

#![allow(unused_imports)]

use crate::Tone;
use crate::Gender;
use crate::Hair;
use crate::Pair;
use crate::emojis::OneOrTwo;
use crate::emojis::TonePair;
use crate::emojis::Family;

pub(crate) fn matching(s: &str) -> Option<&'static crate::Emoji> {
	match s {

		{{ Data }}

		_ => None
	}
}

// EOF